// src/pages/Dashboard.tsx
import { useState, useEffect, useCallback } from "react";
import { ColimaInstance, SystemInfo, dockerApi, volumesApi, networksApi, composeApi, k8sApi, limaApi, LimaInstance, kindApi } from "../lib/api";

type Page = "dashboard" | "instances" | "containers" | "images" | "volumes" | "networks" | "compose" | "kubernetes" | "linux-vms" | "terminal" | "models" | "settings";

interface DashboardProps {
  instances: ColimaInstance[];
  systemInfo: SystemInfo | null;
  loading: boolean;
  onNavigate: (page: Page) => void;
}

const formatBytes = (bytes: number): string => {
  if (bytes >= 1073741824) return `${Math.round(bytes / 1073741824)} GiB`;
  if (bytes >= 1048576) return `${Math.round(bytes / 1048576)} MiB`;
  return `${bytes} B`;
};

export default function Dashboard({ instances, systemInfo, loading, onNavigate }: DashboardProps) {
  const runningCount = instances.filter((i) => i.status === "Running").length;
  const stoppedCount = instances.filter((i) => i.status !== "Running").length;
  const totalCpus = instances.filter(i => i.status === "Running").reduce((sum, i) => sum + i.cpus, 0);

  // Docker resource counts
  const [dockerCounts, setDockerCounts] = useState({ containers: 0, running: 0, images: 0, volumes: 0, networks: 0, composeProjects: 0 });
  // Kubernetes status
  const [k8sStatus, setK8sStatus] = useState({ connected: false, pods: 0, namespaces: 0, kindClusters: 0 });
  // Linux VMs
  const [linuxVMs, setLinuxVMs] = useState<LimaInstance[]>([]);

  const fetchDockerCounts = useCallback(async () => {
    try {
      const [containers, images, volumes, networks, compose] = await Promise.allSettled([
        dockerApi.listContainers(true),
        dockerApi.listImages(),
        volumesApi.listVolumes(),
        networksApi.listNetworks(),
        composeApi.list(),
      ]);
      setDockerCounts({
        containers: containers.status === "fulfilled" ? containers.value.length : 0,
        running: containers.status === "fulfilled" ? containers.value.filter(c => c.State === "running").length : 0,
        images: images.status === "fulfilled" ? images.value.length : 0,
        volumes: volumes.status === "fulfilled" ? volumes.value.length : 0,
        networks: networks.status === "fulfilled" ? networks.value.length : 0,
        composeProjects: compose.status === "fulfilled" ? compose.value.length : 0,
      });
    } catch { /* ignore */ }
  }, []);

  const fetchK8sStatus = useCallback(async () => {
    try {
      const [checkResult, kindRaw] = await Promise.allSettled([
        k8sApi.check(),
        kindApi.list(),
      ]);
      const connected = checkResult.status === "fulfilled";
      let pods = 0, namespaces = 0;
      if (connected) {
        const [nsRaw, podsRaw] = await Promise.allSettled([
          k8sApi.namespaces(),
          k8sApi.pods(""),
        ]);
        if (nsRaw.status === "fulfilled") {
          const ns = nsRaw.value;
          namespaces = Array.isArray(ns) ? ns.length : (typeof ns === "string" ? (ns.match(/"name"/gi) || []).length : 0);
        }
        if (podsRaw.status === "fulfilled") {
          const p = podsRaw.value;
          pods = Array.isArray(p) ? p.length : (typeof p === "string" ? (p.match(/"name"/gi) || []).length : 0);
        }
      }
      const kindClusters = kindRaw.status === "fulfilled"
        ? kindRaw.value.trim().split("\n").filter(Boolean).filter(c => c !== "No kind clusters found.").length
        : 0;
      setK8sStatus({ connected, pods, namespaces, kindClusters });
    } catch { setK8sStatus({ connected: false, pods: 0, namespaces: 0, kindClusters: 0 }); }
  }, []);

  const fetchLinuxVMs = useCallback(async () => {
    try {
      const vms = await limaApi.list();
      setLinuxVMs(vms);
    } catch { setLinuxVMs([]); }
  }, []);

  useEffect(() => {
    if (!loading) {
      fetchDockerCounts();
      fetchK8sStatus();
      fetchLinuxVMs();
    }
  }, [loading, fetchDockerCounts, fetchK8sStatus, fetchLinuxVMs]);

  if (loading) {
    return (
      <div className="loading-screen">
        <div className="spinner" />
        <span>Loading...</span>
      </div>
    );
  }

  return (
    <>
      <div className="content-header">
        <h1>Dashboard</h1>
      </div>

      <div className="content-body">
        {/* Instance Stat Cards */}
        <div className="card-grid" style={{ marginBottom: 24 }}>
          <div className="card stat-card" onClick={() => onNavigate("instances")} style={{ cursor: "pointer" }}>
            <div className="stat-icon" style={{ background: "rgba(88, 166, 255, 0.1)", color: "var(--accent-blue)" }}>
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="2" y="2" width="20" height="8" rx="2"/><rect x="2" y="14" width="20" height="8" rx="2"/>
                <line x1="6" y1="6" x2="6.01" y2="6"/><line x1="6" y1="18" x2="6.01" y2="18"/>
              </svg>
            </div>
            <span className="stat-label">VM Instances</span>
            <span className="stat-value">{instances.length}</span>
          </div>

          <div className="card stat-card">
            <div className="stat-icon" style={{ background: "rgba(63, 185, 80, 0.1)", color: "var(--accent-green)" }}>
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/>
              </svg>
            </div>
            <span className="stat-label">Running VMs</span>
            <span className="stat-value" style={{ color: "var(--accent-green)" }}>{runningCount}</span>
          </div>

          <div className="card stat-card">
            <div className="stat-icon" style={{ background: "rgba(248, 81, 73, 0.1)", color: "var(--accent-red)" }}>
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/>
              </svg>
            </div>
            <span className="stat-label">Stopped VMs</span>
            <span className="stat-value" style={{ color: "var(--accent-red)" }}>{stoppedCount}</span>
          </div>

          <div className="card stat-card">
            <div className="stat-icon" style={{ background: "rgba(188, 140, 255, 0.1)", color: "var(--accent-purple)" }}>
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/>
                <path d="M15 2v2"/><path d="M15 20v2"/><path d="M2 15h2"/><path d="M2 9h2"/><path d="M20 15h2"/><path d="M20 9h2"/><path d="M9 2v2"/><path d="M9 20v2"/>
              </svg>
            </div>
            <span className="stat-label">Total CPUs</span>
            <span className="stat-value">{totalCpus}</span>
          </div>
        </div>

        {/* Docker Resource Overview */}
        <div className="card" style={{ marginBottom: 24 }}>
          <h3 style={{ fontSize: "var(--text-lg)", fontWeight: 600, marginBottom: 16 }}>Docker Resources</h3>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 12 }}>
            <ResourceCard label="Containers" value={dockerCounts.containers} sub={`${dockerCounts.running} running`}
              color="var(--accent-blue)" onClick={() => onNavigate("containers")} />
            <ResourceCard label="Images" value={dockerCounts.images} color="var(--accent-green)" onClick={() => onNavigate("images")} />
            <ResourceCard label="Volumes" value={dockerCounts.volumes} color="var(--accent-purple)" onClick={() => onNavigate("volumes")} />
            <ResourceCard label="Networks" value={dockerCounts.networks} color="var(--accent-orange)" onClick={() => onNavigate("networks")} />
            <ResourceCard label="Compose" value={dockerCounts.composeProjects} color="var(--accent-blue)" onClick={() => onNavigate("compose")} />
          </div>
        </div>

        {/* Kubernetes & Infrastructure */}
        <div className="card" style={{ marginBottom: 24 }}>
          <h3 style={{ fontSize: "var(--text-lg)", fontWeight: 600, marginBottom: 16 }}>Infrastructure</h3>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 12 }}>
            <ResourceCard
              label="Kubernetes"
              value={k8sStatus.connected ? k8sStatus.pods : 0}
              sub={k8sStatus.connected ? `${k8sStatus.namespaces} namespaces` : "Disconnected"}
              color={k8sStatus.connected ? "var(--accent-green)" : "var(--accent-red)"}
              onClick={() => onNavigate("kubernetes")}
            />
            <ResourceCard
              label="Kind Clusters"
              value={k8sStatus.kindClusters}
              color="var(--accent-purple)"
              onClick={() => onNavigate("instances")}
            />
            <ResourceCard
              label="Linux VMs"
              value={linuxVMs.length}
              sub={`${linuxVMs.filter(v => v.status === "Running").length} running`}
              color="var(--accent-orange)"
              onClick={() => onNavigate("linux-vms")}
            />
          </div>
        </div>

        {/* System Info */}
        {systemInfo && (
          <div className="card" style={{ marginBottom: 24 }}>
            <h3 style={{ fontSize: "var(--text-lg)", fontWeight: 600, marginBottom: 16 }}>System Status</h3>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 16 }}>
              <StatusBadge label="Colima" installed={systemInfo.colima_installed} />
              <StatusBadge label="Docker" installed={systemInfo.docker_installed} />
              <StatusBadge label="Lima" installed={systemInfo.lima_installed} />
            </div>
          </div>
        )}

        {/* Quick Instance List */}
        {instances.length > 0 ? (
          <div className="card">
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }}>
              <h3 style={{ fontSize: "var(--text-lg)", fontWeight: 600 }}>Instances</h3>
              <button className="btn btn-ghost" onClick={() => onNavigate("instances")} style={{ fontSize: "var(--text-xs)" }}>
                View All →
              </button>
            </div>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Profile</th><th>Status</th><th>Runtime</th><th>Arch</th><th>Resources</th>
                </tr>
              </thead>
              <tbody>
                {instances.map((inst) => (
                  <tr key={inst.name}>
                    <td style={{ fontWeight: 500 }}>{inst.name}</td>
                    <td>
                      <span className={`badge badge-${inst.status === "Running" ? "running" : "stopped"}`}>
                        <span className="badge-dot" />{inst.status}
                      </span>
                    </td>
                    <td style={{ color: "var(--text-secondary)" }}>{inst.runtime}</td>
                    <td style={{ color: "var(--text-secondary)" }}>{inst.arch}</td>
                    <td style={{ color: "var(--text-secondary)", fontFamily: "var(--font-mono)", fontSize: "var(--text-xs)" }}>
                      {inst.cpus} CPU · {formatBytes(inst.memory)} · {formatBytes(inst.disk)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="empty-state">
            <div className="empty-state-icon">
              <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" style={{ color: "var(--text-muted)" }}>
                <rect x="2" y="2" width="20" height="8" rx="2"/><rect x="2" y="14" width="20" height="8" rx="2"/>
              </svg>
            </div>
            <div className="empty-state-title">No instances found</div>
            <div className="empty-state-text">Create your first Colima instance to get started.</div>
            <button className="btn btn-primary" onClick={() => onNavigate("instances")}>Create Instance</button>
          </div>
        )}
      </div>
    </>
  );
}

function ResourceCard({ label, value, sub, color, onClick }: { label: string; value: number; sub?: string; color: string; onClick: () => void }) {
  return (
    <div onClick={onClick} style={{
      padding: 14, background: "var(--bg-primary)", borderRadius: 8, cursor: "pointer",
      borderLeft: `3px solid ${color}`, transition: "transform 100ms",
    }}>
      <div style={{ fontSize: "var(--text-xs)", color: "var(--text-muted)", marginBottom: 4 }}>{label}</div>
      <div style={{ fontSize: "var(--text-xl)", fontWeight: 700, fontFamily: "var(--font-mono)", color }}>{value}</div>
      {sub && <div style={{ fontSize: "var(--text-xs)", color: "var(--text-muted)", marginTop: 2 }}>{sub}</div>}
    </div>
  );
}

function StatusBadge({ label, installed }: { label: string; installed: boolean }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
      <span className={`badge ${installed ? "badge-running" : "badge-stopped"}`}>
        <span className="badge-dot" />
        {installed ? "Installed" : "Not Found"}
      </span>
      <span style={{ fontSize: "var(--text-sm)", color: "var(--text-secondary)" }}>{label}</span>
    </div>
  );
}

// src/pages/Dashboard.svelte
<script lang="ts">
   
  import { composeApi, k8sApi, limaApi, kindApi, type SystemInfo } from "../lib/api";
  import { dashboardState, dockerState, resourceState } from "../store.svelte";
  import { t } from "../lib/i18n.svelte";

  let { systemInfo, loading, onNavigate } = $props<{
    systemInfo: SystemInfo | null;
    loading: boolean;
    onNavigate: (page: string) => void;
  }>();

  const STALE_MS = 30_000;

  let runningCount = $derived(dashboardState.colimaInstances.filter(i => i.status === "Running").length);
  let stoppedCount = $derived(dashboardState.colimaInstances.filter(i => i.status !== "Running").length);
  let totalCpus = $derived(dashboardState.colimaInstances.filter(i => i.status === "Running").reduce((sum, i) => sum + i.cpus, 0));

  let dockerCounts = $derived({
    containers: dockerState.containers.length,
    running: dockerState.containers.filter(c => c.State === "running").length,
    images: dockerState.images.length,
    volumes: resourceState.volumes.length,
    networks: resourceState.networks.length,
    composeProjects: dashboardState.composeProjectsCount
  });

  function formatBytes(bytes: number) {
    if (bytes >= 1073741824) return `${Math.round(bytes / 1073741824)} GiB`;
    if (bytes >= 1048576) return `${Math.round(bytes / 1048576)} MiB`;
    return `${bytes} B`;
  }

  async function fetchDockerCounts() {
    try {
      const compose = await composeApi.list();
      dashboardState.composeProjectsCount = compose ? compose.length : 0;
    } catch {}
  }

  async function fetchK8sStatus() {
    try {
      const [checkResult, kindRaw] = await Promise.allSettled([k8sApi.check(), kindApi.list()]);
      const connected = checkResult.status === "fulfilled";
      let pods = 0, namespaces = 0;
      if (connected) {
        const [nsRaw, podsRaw] = await Promise.allSettled([k8sApi.namespaces(), k8sApi.pods("")]);
        if (nsRaw.status === "fulfilled") {
          const ns = nsRaw.value;
          namespaces = Array.isArray(ns) ? ns.length : (typeof ns === "string" ? (ns.match(/"name"/gi) || []).length : 0);
        }
        if (podsRaw.status === "fulfilled") {
          const p = podsRaw.value;
          pods = Array.isArray(p) ? p.length : (typeof p === "string" ? (p.match(/"name"/gi) || []).length : 0);
        }
      }
      const kindClusters = kindRaw.status === "fulfilled"
        ? kindRaw.value.trim().split("\n").filter(Boolean).filter(c => c !== "No kind clusters found.").length
        : 0;
      dashboardState.k8sStatus = { connected, pods, namespaces, kindClusters };
    } catch {
      dashboardState.k8sStatus = { connected: false, pods: 0, namespaces: 0, kindClusters: 0 };
    }
  }

  async function fetchLinuxVMs() {
    try {
      dashboardState.linuxVMs = await limaApi.list();
    } catch {
      dashboardState.linuxVMs = [];
    }
  }

  $effect(() => {
    if (!loading) {
      const now = Date.now();
      if (now - dashboardState.lastFetch > STALE_MS) {
        fetchDockerCounts();
        fetchK8sStatus();
        fetchLinuxVMs();
        dashboardState.lastFetch = now;
      }
    }
  });
</script>



<div class="content-header">
  <div class="header-left">
    <h1>{t('dashboard.title', { default: 'Dashboard' })}</h1>
  </div>
</div>

<div class="content-body" style="padding: 24px; max-width: 1200px;">
  {#if loading}
    <div style="display: flex; justify-content: center; align-items: center; height: 200px;">
      <div class="spinner"></div>
      <span style="margin-left: 10px; color: var(--text-muted);">{t('dashboard.loading', { default: 'Loading...' })}</span>
    </div>
  {:else}
    <!-- SECTION 1: Colima Instances -->
    <div class="stat-section">
      <h2 class="section-title">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: var(--accent-blue);"><rect x="2" y="2" width="20" height="8" rx="2" ry="2"></rect><rect x="2" y="14" width="20" height="8" rx="2" ry="2"></rect><line x1="6" y1="6" x2="6.01" y2="6"></line><line x1="6" y1="18" x2="6.01" y2="18"></line></svg>
        {t('dashboard.vm_instances', { default: 'VM Instances' })} 
        <span class="badge">{dashboardState.colimaInstances.length}</span>
      </h2>
      <div class="stats-grid">
        <button class="stat-card" onclick={() => onNavigate("instances")}>
          <div class="stat-title">{t('dashboard.running_vms', { default: 'Running VMs' })}</div>
          <div class="stat-value">{runningCount}</div>
          <div class="stat-icon" style="color: var(--accent-green);">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
          </div>
        </button>
        <button class="stat-card" onclick={() => onNavigate("instances")}>
          <div class="stat-title">{t('dashboard.stopped_vms', { default: 'Stopped VMs' })}</div>
          <div class="stat-value">{stoppedCount}</div>
          <div class="stat-icon" style="color: var(--text-muted);">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
          </div>
        </button>
        <div class="stat-card">
          <div class="stat-title">{t('dashboard.total_cpus', { default: 'Total CPUs' })}</div>
          <div class="stat-value">{totalCpus}</div>
          <div class="stat-icon" style="color: var(--accent-yellow);">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><rect x="9" y="9" width="6" height="6"></rect><line x1="9" y1="1" x2="9" y2="4"></line><line x1="15" y1="1" x2="15" y2="4"></line><line x1="9" y1="20" x2="9" y2="23"></line><line x1="15" y1="20" x2="15" y2="23"></line><line x1="20" y1="9" x2="23" y2="9"></line><line x1="20" y1="14" x2="23" y2="14"></line><line x1="1" y1="9" x2="4" y2="9"></line><line x1="1" y1="14" x2="4" y2="14"></line></svg>
          </div>
        </div>
      </div>
    </div>

    <!-- SECTION 2: Docker Engine -->
    <div class="stat-section">
      <h2 class="section-title">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #2496ed;"><path d="M22 12.8c-.8 0-1.6-.3-2.3-.7-2 1.4-4.5 1.7-6.8 1-2.3.7-4.8.4-6.8-1-.7.4-1.5.7-2.3.7-1.1 0-2.2-.4-3-1.1v4c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2v-4c-.8.7-1.9 1.1-3 1.1z"></path><path d="M12 9c1.7 0 3-1.3 3-3s-1.3-3-3-3-3 1.3-3 3 1.3 3 3 3z"></path></svg>
        Docker Engine
      </h2>
      <div class="stats-grid">
        <button class="stat-card" onclick={() => onNavigate("containers")}>
          <div class="stat-title">{t('dashboard.containers', { default: 'Containers' })}</div>
          <div class="stat-value">
            {dockerCounts.containers}
            <span class="stat-subtitle" style="color: var(--accent-green); margin-left: 8px; font-size: 0.6em;">{dockerCounts.running} {t('dashboard.running', { default: 'Running' })}</span>
          </div>
          <div class="stat-icon" style="color: #2496ed;">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><rect x="9" y="9" width="6" height="6"></rect></svg>
          </div>
        </button>
        <button class="stat-card" onclick={() => onNavigate("images")}>
          <div class="stat-title">{t('dashboard.images', { default: 'Images' })}</div>
          <div class="stat-value">{dockerCounts.images}</div>
          <div class="stat-icon" style="color: var(--text-muted);">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path></svg>
          </div>
        </button>
        <button class="stat-card" onclick={() => onNavigate("volumes")}>
          <div class="stat-title">{t('dashboard.volumes', { default: 'Volumes' })}</div>
          <div class="stat-value">{dockerCounts.volumes}</div>
          <div class="stat-icon" style="color: var(--text-muted);">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"></ellipse><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"></path><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"></path></svg>
          </div>
        </button>
        <button class="stat-card" onclick={() => onNavigate("networks")}>
          <div class="stat-title">{t('dashboard.networks', { default: 'Networks' })}</div>
          <div class="stat-value">{dockerCounts.networks}</div>
          <div class="stat-icon" style="color: var(--text-muted);">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="16" y="16" width="6" height="6" rx="1"></rect><rect x="2" y="16" width="6" height="6" rx="1"></rect><rect x="9" y="2" width="6" height="6" rx="1"></rect><path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"></path><path d="M12 12V8"></path></svg>
          </div>
        </button>
        <button class="stat-card" onclick={() => onNavigate("compose")}>
          <div class="stat-title">{t('dashboard.compose_projects', { default: 'Compose Projects' })}</div>
          <div class="stat-value">{dockerCounts.composeProjects}</div>
          <div class="stat-icon" style="color: var(--text-muted);">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
          </div>
        </button>
      </div>
    </div>

    <!-- Kubernetes & Infrastructure -->
    <div class="card" style="margin-bottom: 24px;">
      <h3 style="font-size: var(--text-lg); font-weight: 600; margin-bottom: 16px;">Infrastructure</h3>
      <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px;">
        
        <button onclick={() => onNavigate("kubernetes")} class="metric-card {dashboardState.k8sStatus.connected ? 'metric-card-green' : 'metric-card-red'}">
          <div class="metric-header">
            <span class="metric-title">Kubernetes</span>
            <div class="metric-icon-wrapper"><svg class="metric-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg></div>
          </div>
          <div class="metric-body">
            <span class="metric-value">{dashboardState.k8sStatus.connected ? dashboardState.k8sStatus.pods : 0}</span>
            <span class="metric-sub">{dashboardState.k8sStatus.connected ? `${dashboardState.k8sStatus.namespaces} namespaces` : "Disconnected"}</span>
          </div>
        </button>

        <button onclick={() => onNavigate("instances")} class="metric-card metric-card-purple">
          <div class="metric-header">
            <span class="metric-title">Kind Clusters</span>
            <div class="metric-icon-wrapper"><svg class="metric-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg></div>
          </div>
          <div class="metric-body">
            <span class="metric-value">{dashboardState.k8sStatus.kindClusters}</span>
            <span class="metric-sub">Local clusters</span>
          </div>
        </button>

        <button onclick={() => onNavigate("linux-vms")} class="metric-card metric-card-orange">
          <div class="metric-header">
            <span class="metric-title">Linux VMs</span>
            <div class="metric-icon-wrapper"><svg class="metric-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg></div>
          </div>
          <div class="metric-body">
            <span class="metric-value">{dashboardState.linuxVMs.length}</span>
            <span class="metric-sub">{dashboardState.linuxVMs.filter(v => v.status === "Running").length} running</span>
          </div>
        </button>
      </div>
    </div>

    <!-- System Info -->
    {#if systemInfo}
      <div class="card" style="margin-bottom: 24px;">
        <h3 style="font-size: var(--text-lg); font-weight: 600; margin-bottom: 16px;">System Status</h3>
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px;">
          <div style="display: flex; align-items: center; gap: 10px;">
            <span class="badge {systemInfo.colima_installed ? 'badge-running' : 'badge-stopped'}"><span class="badge-dot"></span>{systemInfo.colima_installed ? 'Installed' : 'Not Found'}</span>
            <span style="font-size: var(--text-sm); color: var(--text-secondary);">Colima</span>
          </div>
          <div style="display: flex; align-items: center; gap: 10px;">
            <span class="badge {systemInfo.docker_installed ? 'badge-running' : 'badge-stopped'}"><span class="badge-dot"></span>{systemInfo.docker_installed ? 'Installed' : 'Not Found'}</span>
            <span style="font-size: var(--text-sm); color: var(--text-secondary);">Docker</span>
          </div>
          <div style="display: flex; align-items: center; gap: 10px;">
            <span class="badge {systemInfo.lima_installed ? 'badge-running' : 'badge-stopped'}"><span class="badge-dot"></span>{systemInfo.lima_installed ? 'Installed' : 'Not Found'}</span>
            <span style="font-size: var(--text-sm); color: var(--text-secondary);">Lima</span>
          </div>
        </div>
      </div>
    {/if}

    <!-- Quick Instance List -->
    {#if dashboardState.colimaInstances.length > 0}
      <div class="card">
        <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px;">
          <h3 style="font-size: var(--text-lg); font-weight: 600;">Instances</h3>
          <button class="btn btn-ghost" onclick={() => onNavigate("instances")} style="font-size: var(--text-xs);">View All →</button>
        </div>
        <table class="data-table">
          <thead>
            <tr>
              <th>Profile</th><th>Status</th><th>Runtime</th><th>Arch</th><th>Resources</th>
            </tr>
          </thead>
          <tbody>
            {#each dashboardState.colimaInstances as inst}
              <tr>
                <td style="font-weight: 500;">{inst.name}</td>
                <td>
                  <span class="badge {inst.status === 'Running' ? 'badge-running' : 'badge-stopped'}">
                    <span class="badge-dot"></span>{inst.status}
                  </span>
                </td>
                <td style="color: var(--text-secondary);">{inst.runtime}</td>
                <td style="color: var(--text-secondary);">{inst.arch}</td>
                <td style="color: var(--text-secondary); font-family: var(--font-mono); font-size: var(--text-xs);">
                  {inst.cpus} CPU · {formatBytes(inst.memory)} · {formatBytes(inst.disk)}
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {:else}
      <div class="empty-state">
        <div class="empty-state-icon">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" style="color: var(--text-muted);">
            <rect x="2" y="2" width="20" height="8" rx="2"/><rect x="2" y="14" width="20" height="8" rx="2"/>
          </svg>
        </div>
        <div class="empty-state-title">No instances found</div>
        <div class="empty-state-text">Create your first Colima instance to get started.</div>
        <button class="btn btn-primary" onclick={() => onNavigate("instances")}>Create Instance</button>
      </div>
    {/if}
  {/if}
</div>
