// src/pages/Networks.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { networksApi, sysMethods } from "../lib/api";
  import { globalToast } from "../lib/globalToast";
  import { resourceState } from "../store.svelte";
  import * as Icons from "../components/Icons.svelte";
  import { t } from "../lib/i18n.svelte";

  let searchTerm = $state("");
  let showCreate = $state(false);
  let newName = $state("");
  let newDriver = $state("bridge");
  let newSubnet = $state("");
  let actionLoading = $state<string | null>(null);
  let inspecting = $state<string | null>(null);
  let inspectData = $state<string>("");
  let selected = $state<Set<string>>(new Set());
  let batchLoading = $state(false);
  let confirm = $state<{ title: string; message: string; confirmLabel: string; danger: boolean; onConfirm: () => void; onCancel?: () => void } | null>(null);
  let runtimeName = $state("docker");

  async function refreshNetworks() {
    try {
      const list = await networksApi.listNetworks();
      resourceState.networks = list;
    } catch (e) {
      resourceState.networks = [];
    } finally {
      resourceState.networksLoading = false;
    }
  }

  onMount(() => {
    refreshNetworks();
    sysMethods.getRuntimeInfo().then(r => runtimeName = r).catch(() => {});

    const aiListener = async (e: Event) => {
      const customEvent = e as CustomEvent;
      const { payload, resolve } = customEvent.detail;
      const action = customEvent.type.replace("-network", "");
      try {
        if (action === "delete") {
          await executeRemove(payload);
          resolve(`Successfully removed network ${payload}`);
        }
      } catch (err) {
        resolve(`Failed to ${action} network: ${err}`);
      }
    };

    window.addEventListener("delete-network", aiListener);
    return () => window.removeEventListener("delete-network", aiListener);
  });

  $effect(() => {
    if (searchTerm !== undefined) {
      selected = new Set();
    }
  });

  async function handleCreate() {
    if (!newName.trim()) return;
    actionLoading = "create";
    try {
      await networksApi.createNetwork(newName.trim(), newDriver, newSubnet.trim());
      globalToast("success", `Network "${newName}" created`);
      newName = "";
      newSubnet = "";
      showCreate = false;
      refreshNetworks();
    } catch (e) {
      globalToast("error", String(e));
    } finally {
      actionLoading = null;
    }
  }

  async function handleRemove(name: string) {
    confirm = {
      title: "Remove Network", danger: true, confirmLabel: "Remove",
      message: `Remove network "${name}"?`,
      onConfirm: async () => {
        confirm = null;
        try {
          await executeRemove(name);
        } catch (e) {}
      },
      onCancel: () => { confirm = null; }
    };
  }

  async function executeRemove(name: string) {
    actionLoading = name;
    try {
      await networksApi.removeNetwork(name);
      selected = new Set();
      globalToast("success", `Network "${name}" removed`);
      refreshNetworks();
    } catch (e) {
      globalToast("error", String(e));
      throw e;
    } finally {
      actionLoading = null;
    }
  }

  async function handlePrune() {
    confirm = {
      title: "Prune Networks", danger: false, confirmLabel: "Prune All",
      message: "Remove all unused networks?",
      onConfirm: async () => {
        confirm = null;
        actionLoading = "prune";
        try {
          await networksApi.pruneNetworks();
          selected = new Set();
          globalToast("success", "Unused networks pruned");
          refreshNetworks();
        } catch (e) {
          globalToast("error", String(e));
        } finally {
          actionLoading = null;
        }
      },
      onCancel: () => { confirm = null; }
    };
  }

  async function handleInspect(name: string) {
    if (inspecting === name) { inspecting = null; return; }
    try {
      const data = await networksApi.inspectNetwork(name);
      inspectData = data;
      inspecting = name;
    } catch (e) {
      globalToast("error", String(e));
    }
  }

  function isSystemNetwork(name: string) {
    return ["bridge", "host", "none"].includes(name);
  }

  function driverColor(driver: string) {
    switch (driver) {
      case "bridge": return "var(--accent-blue)";
      case "host": return "var(--accent-orange)";
      case "overlay": return "var(--accent-purple)";
      case "null": return "var(--text-muted)";
      default: return "var(--accent-green)";
    }
  }

  async function handleBatchRemove() {
    const targets = filteredNetworks.filter(n => selected.has(n.Id) && !isSystemNetwork(n.Name));
    if (targets.length === 0) return;
    const names = targets.map(n => n.Name);
    confirm = {
      title: "Remove Selected Networks", danger: true, confirmLabel: `Remove ${names.length}`,
      message: `Remove ${names.length} network(s)?\n\n${names.join(", ")}\n\nThis cannot be undone.`,
      onConfirm: async () => {
        confirm = null;
        batchLoading = true;
        let ok_count = 0;
        for (const name of names) {
          try { await networksApi.removeNetwork(name); ok_count++; } catch {}
        }
        selected = new Set();
        batchLoading = false;
        refreshNetworks();
        if (ok_count > 0) {
          globalToast("success", `Removed ${ok_count} network(s)`);
        } else {
          globalToast("error", "Failed to remove selected networks");
        }
      },
      onCancel: () => { confirm = null; }
    };
  }

  function toggleSelect(id: string) {
    const next = new Set(selected);
    next.has(id) ? next.delete(id) : next.add(id);
    selected = next;
  }

  let filteredNetworks = $derived(resourceState.networks.filter(n => 
    n.Name.toLowerCase().includes(searchTerm.toLowerCase()) || 
    n.Driver.toLowerCase().includes(searchTerm.toLowerCase())
  ));

</script>

<div class="content-header">
  <h1>
    {t('networks.title', { default: 'Networks' })}
    <span style="font-size: var(--text-sm); color: var(--text-muted); font-weight: 400; margin-left: 12px;">
      {resourceState.networks.length} {t('networks.count', { default: 'networks' })}
    </span>
    {#if runtimeName}
      <span style="font-size: var(--text-xs); background: var(--bg-secondary); border: 1px solid var(--border-primary); padding: 2px 8px; border-radius: 12px; margin-left: 12px; color: var(--text-muted);">
        {#if runtimeName === "podman"}
          🦭 Podman
        {:else if runtimeName === "containerd"}
          📦 Containerd
        {:else}
          {@html Icons.Docker} Docker
        {/if}
      </span>
    {/if}
  </h1>
  <div class="content-header-actions">
    {#if selected.size > 0}
      <button class="btn btn-ghost" style="color: var(--accent-red); font-size: var(--text-sm);" onclick={handleBatchRemove} disabled={batchLoading}>
        {batchLoading ? t('networks.removing', { default: 'Removing...' }) : t('networks.remove_selected', { default: `Remove ${selected.size} Selected` })}
      </button>
    {/if}
    <button class="btn btn-ghost" onclick={handlePrune} disabled={actionLoading === "prune"}>
      {actionLoading === "prune" ? t('networks.pruning', { default: 'Pruning...' }) : t('networks.prune', { default: 'Prune' })}
    </button>
    <button class="btn btn-primary" onclick={() => showCreate = !showCreate}>
      + {t('networks.create_button', { default: 'Create Network' })}
    </button>
    <button class="btn btn-ghost" onclick={refreshNetworks}>{t('networks.refresh', { default: '↻ Refresh' })}</button>
  </div>
</div>

<div class="content-body">
  {#if showCreate}
    <div style="padding: 16px; background: var(--bg-secondary); border-radius: 12px; margin-bottom: 16px; border: 1px solid var(--border-primary);">
      <h3 style="margin: 0 0 12px; font-size: var(--text-base);">{t('networks.create_title', { default: 'Create Network' })}</h3>
      <div style="display: flex; gap: 12px; align-items: flex-end; flex-wrap: wrap;">
        <div style="flex: 1; min-width: 180px;">
          <label for="netName" style="display: block; font-size: var(--text-sm); color: var(--text-secondary); margin-bottom: 4px;">{t('networks.name', { default: 'Name' })}</label>
          <input id="netName" type="text" bind:value={newName} placeholder="my-network" style="width: 100%; padding: 8px 12px; background: var(--bg-primary); border: 1px solid var(--border-primary); border-radius: 6px; color: var(--text-primary); font-size: var(--text-sm);" onkeydown={(e) => e.key === 'Enter' && handleCreate()} />
        </div>
        <div>
          <label for="netDriver" style="display: block; font-size: var(--text-sm); color: var(--text-secondary); margin-bottom: 4px;">{t('networks.driver', { default: 'Driver' })}</label>
          <select id="netDriver" bind:value={newDriver} class="input select">
            <option value="bridge">bridge</option>
            <option value="host">host</option>
            <option value="overlay">overlay</option>
            <option value="macvlan">macvlan</option>
            <option value="ipvlan">ipvlan</option>
          </select>
        </div>
        <div style="flex: 1; min-width: 180px;">
          <label for="netSubnet" style="display: block; font-size: var(--text-sm); color: var(--text-secondary); margin-bottom: 4px;">{t('networks.subnet', { default: 'Subnet (optional)' })}</label>
          <input id="netSubnet" type="text" bind:value={newSubnet} placeholder="172.28.0.0/16" style="width: 100%; padding: 8px 12px; background: var(--bg-primary); border: 1px solid var(--border-primary); border-radius: 6px; color: var(--text-primary); font-size: var(--text-sm);" onkeydown={(e) => e.key === 'Enter' && handleCreate()} />
        </div>
        <button class="btn btn-primary" onclick={handleCreate} disabled={actionLoading === "create" || !newName.trim()}>
          {actionLoading === "create" ? t('networks.creating', { default: 'Creating...' }) : t('networks.create', { default: 'Create' })}
        </button>
        <button class="btn btn-ghost" onclick={() => showCreate = false}>{t('networks.cancel', { default: 'Cancel' })}</button>
      </div>
    </div>
  {/if}

  <div style="margin-bottom: 16px;">
    <input type="text" bind:value={searchTerm} placeholder={t('networks.search', { default: 'Search networks...' })} style="width: 100%; padding: 8px 12px; background: var(--bg-secondary); border: 1px solid var(--border-primary); border-radius: 8px; color: var(--text-primary); font-size: var(--text-sm);" />
  </div>

  {#if resourceState.networksLoading}
    <div style="text-align: center; padding: 40px; color: var(--text-muted);">{t('networks.loading', { default: 'Loading networks...' })}</div>
  {:else if filteredNetworks.length === 0}
    <div style="text-align: center; padding: 40px; color: var(--text-muted);">
      {searchTerm ? t('networks.no_match', { default: 'No networks match your search' }) : t('networks.no_networks', { default: 'No networks found' })}
    </div>
  {:else}
    <div style="display: flex; flex-direction: column; gap: 8px;">
      {#each filteredNetworks as net (net.Id)}
        <div style="padding: 16px; background: {selected.has(net.Id) ? 'rgba(88,166,255,0.06)' : 'var(--bg-secondary)'}; border-radius: 12px; border: {selected.has(net.Id) ? '1px solid rgba(88,166,255,0.25)' : '1px solid var(--border-primary)'}; transition: all 150ms;">
          <div style="display: flex; justify-content: space-between; align-items: center; gap: 12px;">
            <div style="display: flex; align-items: center; gap: 10px; flex: 1; min-width: 0;">
              {#if isSystemNetwork(net.Name)}
                <input type="checkbox" class="checkbox" disabled checked={false} title="System network — cannot be removed" />
              {:else}
                <input type="checkbox" class="checkbox" checked={selected.has(net.Id)} onchange={() => toggleSelect(net.Id)} />
              {/if}
              <div style="min-width: 0;">
                <div style="display: flex; align-items: center; gap: 8px;">
                  <span style="font-weight: 600; font-size: var(--text-base);">{net.Name}</span>
                  {#if isSystemNetwork(net.Name)}
                    <span style="font-size: var(--text-xs); padding: 2px 6px; border-radius: 4px; background: rgba(139,148,158,0.2); color: var(--text-muted); flex-shrink: 0;">system</span>
                  {/if}
                </div>
                <div style="color: var(--text-muted); font-size: var(--text-sm); margin-top: 4px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                  Driver: <span style="color: {driverColor(net.Driver)};">{net.Driver}</span>
                  {#if net.Scope} · Scope: {net.Scope}{/if}
                  · ID: {net.Id.substring(0, 12)}
                </div>
              </div>
            </div>
            <div style="display: flex; gap: 6px; flex-shrink: 0;">
              <button class="btn btn-ghost" onclick={() => handleInspect(net.Name)} style="font-size: var(--text-xs); padding: 4px 10px;">
                {inspecting === net.Name ? "Hide" : "Inspect"}
              </button>
              {#if !isSystemNetwork(net.Name)}
                <button class="btn btn-ghost" onclick={() => handleRemove(net.Name)} disabled={actionLoading === net.Name} style="font-size: var(--text-xs); padding: 4px 10px; color: var(--accent-red);">
                  {actionLoading === net.Name ? "..." : "Remove"}
                </button>
              {/if}
            </div>
          </div>
          {#if inspecting === net.Name}
            <pre style="margin-top: 12px; padding: 12px; background: var(--bg-primary); border-radius: 8px; font-size: var(--text-xs); overflow: auto; max-height: 300px; color: var(--text-secondary);">{inspectData}</pre>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>

{#if confirm}
  <div role="button" tabindex="0" class="modal-overlay" onkeydown={(e) => e.key === 'Enter' && e.currentTarget.click()} onclick={() => confirm?.onCancel?.()}>
    <div role="button" tabindex="0" class="modal" onkeydown={(e) => e.key === 'Enter' && e.currentTarget.click()} onclick={(e) => e.stopPropagation()} style="width: min(400px, 90vw);">
      <div class="modal-header"><h2 class="modal-title">{confirm.title}</h2></div>
      <p style="color: var(--text-secondary); font-size: var(--text-sm); line-height: 1.6;">{confirm.message}</p>
      <div class="modal-footer">
        <button class="btn btn-ghost" onclick={() => confirm?.onCancel?.()}>Cancel</button>
        <button class="btn {confirm.danger ? 'btn-danger' : 'btn-primary'}" onclick={() => confirm?.onConfirm()}>{confirm.confirmLabel}</button>
      </div>
    </div>
  </div>
{/if}

// src/pages/Networks.tsx
import { useState, useEffect, useCallback } from "react";
import { networksApi, DockerNetwork } from "../lib/api";
import { ConfirmDialog, useConfirm } from "../components/ConfirmDialog";
import { BroomIcon, WarningIcon } from "../components/Icons";

interface NetworksProps {}

export default function Networks(_props: NetworksProps) {
  const [networks, setNetworks] = useState<DockerNetwork[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [newName, setNewName] = useState("");
  const [newDriver, setNewDriver] = useState("bridge");
  const [newSubnet, setNewSubnet] = useState("");
  const [inspecting, setInspecting] = useState<string | null>(null);
  const [inspectData, setInspectData] = useState<string>("");
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [batchLoading, setBatchLoading] = useState(false);
  const { confirm, ConfirmDialogProps } = useConfirm();

  const refresh = useCallback(async () => {
    try {
      setError(null);
      const list = await networksApi.listNetworks();
      setNetworks(list);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  const handleCreate = async () => {
    if (!newName.trim()) return;
    setActionLoading("create");
    try {
      await networksApi.createNetwork(newName.trim(), newDriver, newSubnet.trim());
      setNewName("");
      setNewSubnet("");
      setShowCreate(false);
      await refresh();
    } catch (e) {
      setError(String(e));
    } finally {
      setActionLoading(null);
    }
  };

  const handleRemove = async (name: string) => {
    const ok = await confirm({ title: "Remove Network", message: `Remove network "${name}"?`, confirmText: "Remove", variant: "danger" });
    if (!ok) return;
    setActionLoading(name);
    try {
      await networksApi.removeNetwork(name);
      await refresh();
    } catch (e) {
      setError(String(e));
    } finally {
      setActionLoading(null);
    }
  };

  const handlePrune = async () => {
    const ok = await confirm({ title: "Prune Networks", message: "Remove all unused networks?", confirmText: "Prune All", variant: "warning" });
    if (!ok) return;
    setActionLoading("prune");
    try {
      await networksApi.pruneNetworks();
      await refresh();
    } catch (e) {
      setError(String(e));
    } finally {
      setActionLoading(null);
    }
  };

  const handleInspect = async (name: string) => {
    if (inspecting === name) { setInspecting(null); return; }
    try {
      const data = await networksApi.inspectNetwork(name);
      setInspectData(data);
      setInspecting(name);
    } catch (e) {
      setError(String(e));
    }
  };

  const isSystemNetwork = (name: string) => ["bridge", "host", "none"].includes(name);

  const filtered = networks.filter(n =>
    n.Name.toLowerCase().includes(search.toLowerCase()) ||
    n.Driver.toLowerCase().includes(search.toLowerCase())
  );

  const driverColor = (driver: string) => {
    switch (driver) {
      case "bridge": return "var(--accent-blue)";
      case "host": return "var(--accent-orange)";
      case "overlay": return "var(--accent-purple)";
      case "null": return "var(--text-muted)";
      default: return "var(--accent-green)";
    }
  };

  useEffect(() => { setSelected(new Set()); }, [search]);

  const toggleSelect = (id: string) => setSelected(prev => {
    const next = new Set(prev);
    next.has(id) ? next.delete(id) : next.add(id);
    return next;
  });

  const handleBatchRemove = async () => {
    const names = filtered.filter(n => selected.has(n.Id) && !isSystemNetwork(n.Name)).map(n => n.Name);
    if (names.length === 0) return;
    const ok = await confirm({ title: "Remove Selected Networks", message: `Remove ${names.length} network${names.length > 1 ? "s" : ""}?\n\n${names.join(", ")}\n\nThis cannot be undone.`, confirmText: `Remove ${names.length}`, variant: "danger" });
    if (!ok) return;
    setBatchLoading(true);
    let ok_count = 0;
    for (const name of names) {
      try { await networksApi.removeNetwork(name); ok_count++; } catch { /* continue */ }
    }
    setSelected(new Set());
    setBatchLoading(false);
    refresh();
  };

  return (
    <div style={{ padding: "24px" }}>
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
        <div>
          <h2 style={{ margin: 0, fontSize: "var(--text-xl)", fontWeight: 600 }}>Networks</h2>
          <p style={{ margin: "4px 0 0", color: "var(--text-muted)", fontSize: "var(--text-sm)" }}>
            {networks.length} network{networks.length !== 1 ? "s" : ""}
          </p>
        </div>
        <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
          {selected.size > 0 && (
            <button className="btn btn-ghost" style={{ color: "var(--accent-red)", fontSize: "var(--text-sm)" }}
              onClick={handleBatchRemove} disabled={batchLoading}>
              {batchLoading ? "Removing..." : `Remove ${selected.size} Selected`}
            </button>
          )}
          <button className="btn btn-ghost" onClick={handlePrune} disabled={actionLoading === "prune"}>
            {actionLoading === "prune" ? "Pruning..." : <><BroomIcon size={12} style={{ display: "inline", verticalAlign: "middle" }} /> Prune</>}
          </button>
          <button className="btn btn-primary" onClick={() => setShowCreate(!showCreate)}>
            + Create Network
          </button>
          <button className="btn btn-ghost" onClick={refresh}>↻ Refresh</button>
        </div>
      </div>

      {/* Error */}
      {error && (
        <div style={{ padding: "12px", background: "rgba(248,81,73,0.1)", color: "var(--accent-red)", borderRadius: "8px", marginBottom: "16px", fontSize: "var(--text-sm)" }}>
          <WarningIcon size={14} style={{ display: "inline", verticalAlign: "middle", marginRight: 4 }} /> {error}
          <button className="btn btn-ghost" style={{ marginLeft: "8px", fontSize: "var(--text-xs)" }} onClick={() => setError(null)}>Dismiss</button>
        </div>
      )}

      {/* Create form */}
      {showCreate && (
        <div style={{ padding: "16px", background: "var(--bg-secondary)", borderRadius: "12px", marginBottom: "16px", border: "1px solid var(--border-primary)" }}>
          <h3 style={{ margin: "0 0 12px", fontSize: "var(--text-base)" }}>Create Network</h3>
          <div style={{ display: "flex", gap: "12px", alignItems: "flex-end", flexWrap: "wrap" }}>
            <div style={{ flex: 1, minWidth: "180px" }}>
              <label style={{ display: "block", fontSize: "var(--text-sm)", color: "var(--text-secondary)", marginBottom: "4px" }}>Name</label>
              <input
                type="text"
                value={newName}
                onChange={e => setNewName(e.target.value)}
                placeholder="my-network"
                style={{ width: "100%", padding: "8px 12px", background: "var(--bg-primary)", border: "1px solid var(--border-primary)", borderRadius: "6px", color: "var(--text-primary)", fontSize: "var(--text-sm)" }}
                onKeyDown={e => e.key === "Enter" && handleCreate()}
              />
            </div>
            <div>
              <label style={{ display: "block", fontSize: "var(--text-sm)", color: "var(--text-secondary)", marginBottom: "4px" }}>Driver</label>
              <select
                value={newDriver}
                onChange={e => setNewDriver(e.target.value)}
                style={{ padding: "8px 12px", background: "var(--bg-primary)", border: "1px solid var(--border-primary)", borderRadius: "6px", color: "var(--text-primary)", fontSize: "var(--text-sm)" }}
              >
                <option value="bridge">bridge</option>
                <option value="host">host</option>
                <option value="overlay">overlay</option>
                <option value="macvlan">macvlan</option>
                <option value="ipvlan">ipvlan</option>
              </select>
            </div>
            <div style={{ flex: 1, minWidth: "180px" }}>
              <label style={{ display: "block", fontSize: "var(--text-sm)", color: "var(--text-secondary)", marginBottom: "4px" }}>Subnet (optional)</label>
              <input
                type="text"
                value={newSubnet}
                onChange={e => setNewSubnet(e.target.value)}
                placeholder="172.28.0.0/16"
                style={{ width: "100%", padding: "8px 12px", background: "var(--bg-primary)", border: "1px solid var(--border-primary)", borderRadius: "6px", color: "var(--text-primary)", fontSize: "var(--text-sm)" }}
              />
            </div>
            <button className="btn btn-primary" onClick={handleCreate} disabled={actionLoading === "create" || !newName.trim()}>
              {actionLoading === "create" ? "Creating..." : "Create"}
            </button>
            <button className="btn btn-ghost" onClick={() => setShowCreate(false)}>Cancel</button>
          </div>
        </div>
      )}

      {/* Search */}
      <div style={{ marginBottom: "16px" }}>
        <input
          type="text"
          value={search}
          onChange={e => setSearch(e.target.value)}
          placeholder="Search networks..."
          style={{ width: "100%", padding: "8px 12px", background: "var(--bg-secondary)", border: "1px solid var(--border-primary)", borderRadius: "8px", color: "var(--text-primary)", fontSize: "var(--text-sm)" }}
        />
      </div>

      {/* Network list */}
      {loading ? (
        <div style={{ textAlign: "center", padding: "40px", color: "var(--text-muted)" }}>Loading networks...</div>
      ) : filtered.length === 0 ? (
        <div style={{ textAlign: "center", padding: "40px", color: "var(--text-muted)" }}>
          {search ? "No networks match your search" : "No networks found"}
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
          {filtered.map(net => (
            <div key={net.Id} style={{ padding: "16px", background: selected.has(net.Id) ? "rgba(88,166,255,0.06)" : "var(--bg-secondary)", borderRadius: "12px", border: selected.has(net.Id) ? "1px solid rgba(88,166,255,0.25)" : "1px solid var(--border-primary)", transition: "all 150ms" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  {isSystemNetwork(net.Name) ? (
                    <input type="checkbox" disabled checked={false}
                      title="System network — cannot be removed"
                      style={{ opacity: 0.3, cursor: "not-allowed" }} />
                  ) : (
                    <input type="checkbox" checked={selected.has(net.Id)} onChange={() => toggleSelect(net.Id)}
                      style={{ accentColor: "var(--accent-blue)", cursor: "pointer" }} />
                  )}
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                    <span style={{ fontWeight: 600, fontSize: "var(--text-base)" }}>{net.Name}</span>
                    {isSystemNetwork(net.Name) && (
                      <span style={{ fontSize: "var(--text-xs)", padding: "2px 6px", borderRadius: "4px", background: "rgba(139,148,158,0.2)", color: "var(--text-muted)" }}>
                        system
                      </span>
                    )}
                  </div>
                  <div style={{ color: "var(--text-muted)", fontSize: "var(--text-sm)", marginTop: "4px" }}>
                    Driver: <span style={{ color: driverColor(net.Driver) }}>{net.Driver}</span>
                    {net.Scope && <> · Scope: {net.Scope}</>}
                    <> · ID: {net.Id.substring(0, 12)}</>
                  </div>
                </div>
                <div style={{ display: "flex", gap: "6px" }}>
                  <button className="btn btn-ghost" onClick={() => handleInspect(net.Name)} style={{ fontSize: "var(--text-xs)", padding: "4px 10px" }}>
                    {inspecting === net.Name ? "Hide" : "Inspect"}
                  </button>
                  {!isSystemNetwork(net.Name) && (
                    <button
                      className="btn btn-ghost"
                      onClick={() => handleRemove(net.Name)}
                      disabled={actionLoading === net.Name}
                      style={{ fontSize: "var(--text-xs)", padding: "4px 10px", color: "var(--accent-red)" }}
                    >
                      {actionLoading === net.Name ? "..." : "Remove"}
                    </button>
                  )}
                </div>
              </div>
              </div>
              {inspecting === net.Name && (
                <pre style={{ marginTop: "12px", padding: "12px", background: "var(--bg-primary)", borderRadius: "8px", fontSize: "var(--text-xs)", overflow: "auto", maxHeight: "300px", color: "var(--text-secondary)" }}>
                  {inspectData}
                </pre>
              )}
            </div>
          ))}
        </div>
      )}
      <ConfirmDialog {...ConfirmDialogProps} />
    </div>
  );
}
