// src/pages/Terminal.tsx
import { useState, useEffect, useRef } from "react";
import { Terminal as XTerm } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import { CloseIcon } from "../components/Icons";
import { WebLinksAddon } from "@xterm/addon-web-links";
import "@xterm/xterm/css/xterm.css";
import { colimaApi, ColimaInstance, limaApi, LimaInstance } from "../lib/api";

const API_BASE = "http://127.0.0.1:11420";


interface TerminalTab {
  id: string;
  label: string;
  profile: string;
  vmType: "colima" | "lima";
}

/* ===== Terminal Theme (shared) ===== */
const termTheme = {
  background: "#0D1117",
  foreground: "#E6EDF3",
  cursor: "#58A6FF",
  selectionBackground: "rgba(88, 166, 255, 0.3)",
  black: "#0D1117",
  red: "#F85149",
  green: "#3FB950",
  yellow: "#D29922",
  blue: "#58A6FF",
  magenta: "#BC8CFF",
  cyan: "#39D2C0",
  white: "#E6EDF3",
  brightBlack: "#6E7681",
  brightRed: "#F85149",
  brightGreen: "#3FB950",
  brightYellow: "#D29922",
  brightBlue: "#58A6FF",
  brightMagenta: "#BC8CFF",
  brightCyan: "#39D2C0",
  brightWhite: "#FFFFFF",
};

/* ===== Browser Mode Terminal (HTTP Polling) ===== */
function BrowserTerminalInstance({
  profile,
  active,
  sessionId,
  vmType = "colima",
}: {
  profile: string;
  active: boolean;
  sessionId: string;
  vmType?: "colima" | "lima";
}) {
  const termRef = useRef<HTMLDivElement>(null);
  const xtermRef = useRef<XTerm | null>(null);
  const fitRef = useRef<FitAddon | null>(null);
  const pollingRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const mountedRef = useRef(true);
  const [connected, setConnected] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    mountedRef.current = true;
    // Generate unique session ID per mount to avoid React StrictMode race
    // (cleanup's async close from mount1 won't kill mount2's session)
    const actualSessionId = `${sessionId}-${Date.now()}`;
    if (!termRef.current || xtermRef.current) return;

    const xterm = new XTerm({
      cursorBlink: true,
      fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
      fontSize: 13,
      lineHeight: 1.4,
      theme: termTheme,
    });

    const fit = new FitAddon();
    fitRef.current = fit;
    xterm.loadAddon(fit);
    xterm.loadAddon(new WebLinksAddon());

    xterm.open(termRef.current);
    fit.fit();
    xtermRef.current = xterm;

    const resizeObserver = new ResizeObserver(() => {
      if (fitRef.current) {
        try { fitRef.current.fit(); } catch (_) { /* ignore */ }
      }
    });
    resizeObserver.observe(termRef.current);

    // Connect via HTTP API
    const connect = async () => {
      xterm.writeln("\x1b[36m● Connecting to " + profile + " (browser mode)...\x1b[0m\r\n");

      try {
        // Try to close any existing session with same ID first (handles React StrictMode double-mount)
        await fetch(`${API_BASE}/api/terminal/close`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ session_id: actualSessionId }),
        }).catch(() => {});

        const res = await fetch(`${API_BASE}/api/terminal/create`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ session_id: actualSessionId, profile, vm_type: vmType }),
        });
        const data = await res.json();

        if (!mountedRef.current) return; // Component was unmounted during await

        if (!data.success) {
          throw new Error(data.error || "Failed to create session");
        }

        setConnected(true);

        // Send user input to backend
        xterm.onData(async (input) => {
          try {
            await fetch(`${API_BASE}/api/terminal/write`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ session_id: actualSessionId, data: input }),
            });
          } catch (_) { /* ignore write errors */ }
        });

        // Poll for output every 100ms
        pollingRef.current = setInterval(async () => {
          if (!mountedRef.current) return;
          try {
            const r = await fetch(`${API_BASE}/api/terminal/read?session_id=${encodeURIComponent(actualSessionId)}`);
            const d = await r.json();
            if (d.success && d.data) {
              // Normalize line endings: convert bare \n to \r\n for xterm.js
              const normalized = d.data.replace(/\r?\n/g, "\r\n");
              xterm.write(normalized);
            }
          } catch (_) { /* ignore read errors */ }
        }, 100);

      } catch (e) {
        if (!mountedRef.current) return;
        xterm.writeln(`\r\n\x1b[31m● Failed to connect: ${e}\x1b[0m`);
        xterm.writeln("\x1b[33m  Make sure the instance is running.\x1b[0m");
        setError(String(e));
      }
    };

    connect();

    return () => {
      mountedRef.current = false;
      resizeObserver.disconnect();
      // Cleanup: stop polling and close session
      if (pollingRef.current) {
        clearInterval(pollingRef.current);
        pollingRef.current = null;
      }
      fetch(`${API_BASE}/api/terminal/close`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ session_id: actualSessionId }),
      }).catch(() => {});
      if (xtermRef.current) {
        xtermRef.current.dispose();
        xtermRef.current = null;
      }
    };
  }, [sessionId, profile, vmType]); // Only re-run on session/profile/vmType change

  // Re-fit when tab becomes active
  useEffect(() => {
    if (active && fitRef.current) {
      setTimeout(() => {
        try { fitRef.current?.fit(); } catch (_) { /* ignore */ }
      }, 100);
    }
  }, [active]);

  return (
    <div style={{ position: "relative", height: "100%", display: active ? "block" : "none" }}>
      {error && !connected && (
        <div style={{
          position: "absolute", top: 12, right: 12, zIndex: 10,
          padding: "6px 12px", borderRadius: "var(--radius-md)",
          background: "rgba(248, 81, 73, 0.15)", border: "1px solid var(--accent-red)",
          color: "var(--accent-red)", fontSize: "var(--text-xs)",
        }}>
          Connection failed
        </div>
      )}
      <div ref={termRef} style={{ height: "100%", padding: 4 }} />
    </div>
  );
}



/* ===== Main Terminal Page ===== */
export default function TerminalPage() {
  const [tabs, setTabs] = useState<TerminalTab[]>([]);
  const [activeTab, setActiveTab] = useState<string | null>(null);
  const [instances, setInstances] = useState<ColimaInstance[]>([]);
  const [limaVMs, setLimaVMs] = useState<LimaInstance[]>([]);
  const [showPicker, setShowPicker] = useState(false);

  useEffect(() => {
    const load = async () => {
      try {
        const list = await colimaApi.listInstances();
        setInstances(list.filter((i) => i.status === "Running"));
      } catch (_) { /* ignore */ }
      try {
        const vms = await limaApi.list();
        setLimaVMs(vms.filter((v) => v.status === "Running"));
      } catch (_) { /* ignore */ }
    };
    load();
    const interval = setInterval(load, 10000);
    return () => clearInterval(interval);
  }, []);

  const addTab = (profile: string, vmType: "colima" | "lima" = "colima") => {
    const id = `term-${Date.now()}`;
    const label = vmType === "lima" ? `🐧 ${profile}` : (profile === "default" ? "colima" : profile);
    setTabs((prev) => [...prev, { id, label, profile, vmType }]);
    setActiveTab(id);
    setShowPicker(false);
  };

  const removeTab = (id: string) => {
    setTabs((prev) => {
      const next = prev.filter((t) => t.id !== id);
      if (activeTab === id) {
        setActiveTab(next.length > 0 ? next[next.length - 1].id : null);
      }
      return next;
    });
  };

  const runningInstances = instances.filter((i) => i.status === "Running");
  const runningLimaVMs = limaVMs.filter((v) => v.status === "Running");
  const hasRunning = runningInstances.length > 0 || runningLimaVMs.length > 0;

  return (
    <>
      <div className="content-header">
        <h1>Terminal</h1>
        <div className="content-header-actions">
          <button className="btn btn-primary" onClick={() => {
            if (runningInstances.length + runningLimaVMs.length === 1) {
              if (runningInstances.length === 1) {
                const name = runningInstances[0].name;
                addTab(name === "colima" ? "default" : name.replace("colima-", ""), "colima");
              } else {
                addTab(runningLimaVMs[0].name, "lima");
              }
            } else {
              setShowPicker(true);
            }
          }}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
            </svg>
            New Session
          </button>
        </div>
      </div>

      {/* Tab Bar */}
      {tabs.length > 0 && (
        <div style={{
          display: "flex", alignItems: "center", gap: 0,
          borderBottom: "1px solid var(--border-primary)",
          background: "var(--bg-content)",
          paddingLeft: 12, flexShrink: 0, overflow: "auto",
        }}>
          {tabs.map((tab) => (
            <div
              key={tab.id}
              style={{
                display: "flex", alignItems: "center", gap: 6,
                padding: "8px 12px",
                borderBottom: activeTab === tab.id ? "2px solid var(--accent-blue)" : "2px solid transparent",
                color: activeTab === tab.id ? "var(--text-primary)" : "var(--text-secondary)",
                cursor: "pointer", fontSize: "var(--text-sm)",
                fontWeight: activeTab === tab.id ? 600 : 400,
                whiteSpace: "nowrap", transition: "all 150ms",
              }}
              onClick={() => setActiveTab(tab.id)}
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/>
              </svg>
              {tab.label}
              <span
                style={{ marginLeft: 4, opacity: 0.5, cursor: "pointer", fontSize: "var(--text-xs)" }}
                onClick={(e) => { e.stopPropagation(); removeTab(tab.id); }}
              >
                <CloseIcon size={10} />
              </span>
            </div>
          ))}
        </div>
      )}

      {/* Terminal Content */}
      <div style={{ flex: 1, overflow: "hidden", background: "#0D1117" }}>
        {tabs.length === 0 ? (
          <div className="empty-state" style={{ height: "100%" }}>
            <div className="empty-state-icon">
              <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" style={{ color: "var(--text-muted)" }}>
                <polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/>
              </svg>
            </div>
            <div className="empty-state-title">No terminal sessions</div>
            <div className="empty-state-text">
              Open a new SSH session to a running instance.
            </div>
            {hasRunning ? (
              <button className="btn btn-primary" onClick={() => {
                if (runningInstances.length + runningLimaVMs.length === 1) {
                  if (runningInstances.length === 1) {
                    const name = runningInstances[0].name;
                    addTab(name === "colima" ? "default" : name.replace("colima-", ""), "colima");
                  } else {
                    addTab(runningLimaVMs[0].name, "lima");
                  }
                } else {
                  setShowPicker(true);
                }
              }}>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
                </svg>
                New Session
              </button>
            ) : (
              <p style={{ fontSize: "var(--text-xs)", color: "var(--text-muted)" }}>
                No running instances. Start an instance first.
              </p>
            )}
          </div>
        ) : (
          tabs.map((tab) =>
              <BrowserTerminalInstance key={tab.id} profile={tab.profile} active={activeTab === tab.id} sessionId={tab.id} vmType={tab.vmType} />
          )
        )}
      </div>

      {/* Instance Picker Modal */}
      {showPicker && (
        <div className="modal-overlay" onClick={() => setShowPicker(false)}>
          <div className="modal" onClick={(e) => e.stopPropagation()} style={{ width: "min(400px, 90vw)" }}>
            <div className="modal-header">
              <h2 className="modal-title">Select Instance</h2>
              <button className="btn btn-icon btn-ghost" onClick={() => setShowPicker(false)}><CloseIcon size={16} /></button>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
              {runningInstances.length > 0 && (
                <div style={{ fontSize: "var(--text-xs)", color: "var(--text-muted)", padding: "8px 16px 4px", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em" }}>
                  Colima Instances
                </div>
              )}
              {runningInstances.map((inst) => {
                const instProfile = inst.name === "colima" ? "default" : inst.name.replace("colima-", "");
                return (
                  <div
                    key={`colima-${inst.name}`}
                    className="nav-item"
                    style={{ padding: "12px 16px", borderRadius: "var(--radius-md)" }}
                    onClick={() => addTab(instProfile, "colima")}
                  >
                    <div style={{ width: 8, height: 8, borderRadius: "50%", background: "var(--status-running)", boxShadow: "0 0 6px var(--status-running)" }} />
                    <div>
                      <div style={{ fontWeight: 500 }}>{inst.name}</div>
                      <div style={{ fontSize: "var(--text-xs)", color: "var(--text-muted)" }}>
                        {inst.runtime} · {inst.arch} · {inst.cpus} CPU
                      </div>
                    </div>
                  </div>
                );
              })}
              {runningLimaVMs.length > 0 && (
                <div style={{ fontSize: "var(--text-xs)", color: "var(--text-muted)", padding: "8px 16px 4px", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", borderTop: runningInstances.length > 0 ? "1px solid var(--border-primary)" : "none", marginTop: runningInstances.length > 0 ? 4 : 0 }}>
                  Linux VMs (Lima)
                </div>
              )}
              {runningLimaVMs.map((vm) => (
                <div
                  key={`lima-${vm.name}`}
                  className="nav-item"
                  style={{ padding: "12px 16px", borderRadius: "var(--radius-md)" }}
                  onClick={() => addTab(vm.name, "lima")}
                >
                  <div style={{ width: 8, height: 8, borderRadius: "50%", background: "var(--status-running)", boxShadow: "0 0 6px var(--status-running)" }} />
                  <div>
                    <div style={{ fontWeight: 500 }}>🐧 {vm.name}</div>
                    <div style={{ fontSize: "var(--text-xs)", color: "var(--text-muted)" }}>
                      {vm.arch} · {vm.cpus} CPU · {vm.memory}
                    </div>
                  </div>
                </div>
              ))}
              {!hasRunning && (
                <p style={{ textAlign: "center", color: "var(--text-muted)", padding: 20, fontSize: "var(--text-sm)" }}>
                  No running instances available.
                </p>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// src/pages/Terminal.svelte
<script lang="ts">
  import { dashboardState } from "../store.svelte";
  import Icon from "../components/Icon.svelte";
  import { getApiToken } from "../lib/api";
  import { t } from "../lib/i18n.svelte";
  import TerminalInstance from "./TerminalInstance.svelte";

  const API_BASE = "http://127.0.0.1:11420";

  async function authHeaders(): Promise<Record<string, string>> {
    const token = await getApiToken();
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (token) {
      headers["Authorization"] = `Bearer ${token}`;
    }
    return headers;
  }

  interface TerminalTab {
    id: string;
    label: string;
    profile: string;
    vmType: "colima" | "lima";
  }

  const termTheme = {
    background: "#0D1117",
    foreground: "#E6EDF3",
    cursor: "#58A6FF",
    selectionBackground: "rgba(88, 166, 255, 0.3)",
    black: "#0D1117",
    red: "#F85149",
    green: "#3FB950",
    yellow: "#D29922",
    blue: "#58A6FF",
    magenta: "#BC8CFF",
    cyan: "#39D2C0",
    white: "#E6EDF3",
    brightBlack: "#6E7681",
    brightRed: "#F85149",
    brightGreen: "#3FB950",
    brightYellow: "#D29922",
    brightBlue: "#58A6FF",
    brightMagenta: "#BC8CFF",
    brightCyan: "#39D2C0",
    brightWhite: "#FFFFFF",
  };

  let tabs = $state<TerminalTab[]>([]);
  let activeTab = $state<string | null>(null);
  let showPicker = $state(false);

  let instances = $derived(dashboardState.colimaInstances.filter(i => i.status === "Running"));
  let limaVMs = $derived(dashboardState.linuxVMs.filter(v => v.status === "Running"));

  let hasRunning = $derived(instances.length > 0 || limaVMs.length > 0);

  function addTab(profile: string, vmType: "colima" | "lima" = "colima") {
    const id = `term-${Date.now()}`;
    const label = vmType === "lima" ? `🐧 ${profile}` : (profile === "default" ? "colima" : profile);
    tabs = [...tabs, { id, label, profile, vmType }];
    activeTab = id;
    showPicker = false;
  }

  function removeTab(id: string) {
    const next = tabs.filter(t => t.id !== id);
    if (activeTab === id) {
      activeTab = next.length > 0 ? next[next.length - 1].id : null;
    }
    tabs = next;
  }
</script>

<div class="content-header">
  <h1>{t('terminal.title', { default: 'Terminal' })}</h1>
  <div class="content-header-actions">
    <button class="btn btn-primary" onclick={() => {
      if (instances.length + limaVMs.length === 1) {
        if (instances.length === 1) {
          const name = instances[0].name;
          addTab(name === "colima" ? "default" : name.replace("colima-", ""), "colima");
        } else {
          addTab(limaVMs[0].name, "lima");
        }
      } else {
        showPicker = true;
      }
    }}>
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
      </svg>
      {t('terminal.new_session', { default: 'New Session' })}
    </button>
  </div>
</div>

<!-- Tab Bar -->
{#if tabs.length > 0}
  <div style="display: flex; align-items: center; gap: 0; border-bottom: 1px solid var(--border-primary); background: var(--bg-content); padding-left: 12px; flex-shrink: 0; overflow: auto;">
    {#each tabs as tab (tab.id)}
      <div
        style="display: flex; align-items: center; gap: 6px; padding: 8px 12px; border-bottom: {activeTab === tab.id ? '2px solid var(--accent-blue)' : '2px solid transparent'}; color: {activeTab === tab.id ? 'var(--text-primary)' : 'var(--text-secondary)'}; cursor: pointer; font-size: var(--text-sm); font-weight: {activeTab === tab.id ? 600 : 400}; white-space: nowrap; transition: all 150ms;"
        onclick={() => activeTab = tab.id}
      >
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/>
        </svg>
        {tab.label}
        <span
          style="margin-left: 4px; opacity: 0.5; cursor: pointer; font-size: var(--text-xs);"
          onclick={(e) => { e.stopPropagation(); removeTab(tab.id); }}
        >
          <Icon name="Close" size={10} />
        </span>
      </div>
    {/each}
  </div>
{/if}

<!-- Terminal Content -->
<div style="flex: 1; overflow: hidden; background: #0D1117; display: flex; flex-direction: column;">
  {#if tabs.length === 0}
    <div class="empty-state" style="height: 100%;">
      <div class="empty-state-icon">
        <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" style="color: var(--text-muted);">
          <polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/>
        </svg>
      </div>
      <div class="empty-state-title">{t('terminal.no_sessions', { default: 'No terminal sessions' })}</div>
      <div class="empty-state-text">
        {t('terminal.instructions', { default: 'Open a new SSH session to a running instance.' })}
      </div>
      {#if hasRunning}
        <button class="btn btn-primary" onclick={() => {
          if (instances.length + limaVMs.length === 1) {
            if (instances.length === 1) {
              const name = instances[0].name;
              addTab(name === "colima" ? "default" : name.replace("colima-", ""), "colima");
            } else {
              addTab(limaVMs[0].name, "lima");
            }
          } else {
            showPicker = true;
          }
        }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
          </svg>
          New Session
        </button>
      {:else}
        <p style="font-size: var(--text-xs); color: var(--text-muted);">
          No running instances. Start an instance first.
        </p>
      {/if}
    </div>
  {:else}
    {#each tabs as tab (tab.id)}
      <div style="display: {activeTab === tab.id ? 'block' : 'none'}; flex: 1; position: relative;">
        <!-- BrowserTerminalInstance component logic embedded -->
        {#if tab.id}
          {@const sessionId = tab.id}
          {@const profile = tab.profile}
          {@const vmType = tab.vmType}
          <!-- Create a nested wrapper component for each terminal instance -->
          <TerminalInstance {sessionId} {profile} {vmType} active={activeTab === tab.id} {termTheme} {authHeaders} {API_BASE} />
        {/if}
      </div>
    {/each}
  {/if}
</div>

<!-- Instance Picker Modal -->
{#if showPicker}
  <div role="button" tabindex="0" class="modal-overlay" onkeydown={(e) => e.key === 'Enter' && e.currentTarget.click()} onclick={() => showPicker = false}>
    <div role="button" tabindex="0" class="modal" onkeydown={(e) => e.key === 'Enter' && e.currentTarget.click()} onclick={(e) => e.stopPropagation()} style="width: min(400px, 90vw);">
      <div class="modal-header">
        <h2 class="modal-title">Select Instance</h2>
        <button class="btn btn-icon btn-ghost" onclick={() => showPicker = false}><Icon name="Close" size={16} /></button>
      </div>
      <div style="display: flex; flex-direction: column; gap: 4px;">
        {#if instances.length > 0}
          <div style="font-size: var(--text-xs); color: var(--text-muted); padding: 8px 16px 4px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;">
            Colima Instances
          </div>
        {/if}
        {#each instances as inst}
          <div
            class="nav-item"
            style="padding: 12px 16px; border-radius: var(--radius-md);"
            onclick={() => addTab(inst.name === "colima" ? "default" : inst.name.replace("colima-", ""), "colima")}
          >
            <div style="width: 8px; height: 8px; border-radius: 50%; background: var(--status-running); box-shadow: 0 0 6px var(--status-running);"></div>
            <div>
              <div style="font-weight: 500;">{inst.name}</div>
              <div style="font-size: var(--text-xs); color: var(--text-muted);">
                {inst.runtime} · {inst.arch} · {inst.cpus} CPU
              </div>
            </div>
          </div>
        {/each}
        {#if limaVMs.length > 0}
          <div style="font-size: var(--text-xs); color: var(--text-muted); padding: 8px 16px 4px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; border-top: {instances.length > 0 ? '1px solid var(--border-primary)' : 'none'}; margin-top: {instances.length > 0 ? 4 : 0}px;">
            Linux VMs (Lima)
          </div>
        {/if}
        {#each limaVMs as vm}
          <div
            class="nav-item"
            style="padding: 12px 16px; border-radius: var(--radius-md);"
            onclick={() => addTab(vm.name, "lima")}
          >
            <div style="width: 8px; height: 8px; border-radius: 50%; background: var(--status-running); box-shadow: 0 0 6px var(--status-running);"></div>
            <div>
              <div style="font-weight: 500;">🐧 {vm.name}</div>
              <div style="font-size: var(--text-xs); color: var(--text-muted);">
                {vm.arch} · {vm.cpus} CPU · {vm.memory}
              </div>
            </div>
          </div>
        {/each}
        {#if !hasRunning}
          <p style="text-align: center; color: var(--text-muted); padding: 20px; font-size: var(--text-sm);">
            No running instances available.
          </p>
        {/if}
      </div>
    </div>
  </div>
{/if}
