// src/pages/Volumes.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { volumesApi, sysMethods } from "../lib/api";
  import { globalToast } from "../lib/globalToast";
  import { t } from "../lib/i18n.svelte";
  import { resourceState } from "../store.svelte";
  import * as Icons from "../components/Icons.svelte";
  import { formatVolumeName } from "../lib/formatters";

  let searchTerm = $state("");
  let showCreate = $state(false);
  let newName = $state("");
  let newDriver = $state("local");
  let actionLoading = $state<string | null>(null);
  let inspecting = $state<string | null>(null);
  let inspectData = $state<string>("");
  let selected = $state<Set<string>>(new Set());
  let batchLoading = $state(false);
  let confirm = $state<{ title: string; message: string; confirmLabel: string; danger: boolean; onConfirm: () => void; onCancel?: () => void } | null>(null);
  let runtimeName = $state("docker");

  async function refreshVolumes() {
    try {
      const list = await volumesApi.listVolumes();
      resourceState.volumes = list;
    } catch (e) {
      resourceState.volumes = [];
    } finally {
      resourceState.volumesLoading = false;
    }
  }

  onMount(() => {
    refreshVolumes();
    sysMethods.getRuntimeInfo().then(r => runtimeName = r).catch(() => {});

    const aiListener = async (e: Event) => {
      const customEvent = e as CustomEvent;
      const { payload, resolve } = customEvent.detail;
      const action = customEvent.type.replace("-volume", "");
      try {
        if (action === "delete") {
          await executeRemove(payload);
          resolve(`Successfully removed volume ${payload}`);
        }
      } catch (err) {
        resolve(`Failed to ${action} volume: ${err}`);
      }
    };

    window.addEventListener("delete-volume", aiListener);
    return () => window.removeEventListener("delete-volume", aiListener);
  });

  $effect(() => {
    // Clear selection on search change
    if (searchTerm !== undefined) {
      selected = new Set();
    }
  });

  async function handleCreate() {
    if (!newName.trim()) return;
    actionLoading = "create";
    try {
      await volumesApi.createVolume(newName.trim(), newDriver);
      globalToast("success", `Volume "${newName}" created`);
      newName = "";
      showCreate = false;
      refreshVolumes();
    } catch (e) {
      globalToast("error", String(e));
    } finally {
      actionLoading = null;
    }
  }

  async function handleRemove(name: string) {
    confirm = {
      title: t("volumes.remove_title", { default: "Remove Volume" }), danger: true, confirmLabel: t("volumes.remove_action", { default: "Remove" }),
      message: t("volumes.remove_confirm", { default: `Remove volume "${name}"?` }),
      onConfirm: async () => {
        confirm = null;
        try {
          await executeRemove(name);
        } catch (e) {}
      },
      onCancel: () => { confirm = null; }
    };
  }

  async function executeRemove(name: string) {
    actionLoading = name;
    try {
      await volumesApi.removeVolume(name, true);
      selected = new Set();
      globalToast("success", `Volume "${name}" removed`);
      refreshVolumes();
    } catch (e) {
      globalToast("error", String(e));
      throw e;
    } finally {
      actionLoading = null;
    }
  }

  async function handlePrune() {
    confirm = {
      title: t("volumes.prune_title", { default: "Prune Volumes" }), danger: false, confirmLabel: t("volumes.prune_action", { default: "Prune All" }),
      message: t("volumes.prune_confirm", { default: "Remove all unused volumes? This cannot be undone." }),
      onConfirm: async () => {
        confirm = null;
        actionLoading = "prune";
        try {
          await volumesApi.pruneVolumes();
          selected = new Set();
          globalToast("success", "Unused volumes pruned");
          refreshVolumes();
        } catch (e) {
          globalToast("error", String(e));
        } finally {
          actionLoading = null;
        }
      },
      onCancel: () => { confirm = null; }
    };
  }

  async function handleInspect(name: string) {
    if (inspecting === name) { inspecting = null; return; }
    try {
      const data = await volumesApi.inspectVolume(name);
      inspectData = data;
      inspecting = name;
    } catch (e) {
      globalToast("error", String(e));
    }
  }

  async function handleBatchRemove() {
    const targets = filteredVolumes.filter(v => selected.has(v.Name));
    if (targets.length === 0) return;
    const names = targets.map(v => v.Name);
    confirm = {
      title: t("volumes.remove_selected_title", { default: "Remove Selected Volumes" }), danger: true, confirmLabel: t("volumes.remove_count", { default: `Remove ${names.length}`, count: names.length }),
      message: t("volumes.remove_batch_confirm", { default: `Remove ${names.length} volume(s)?\n\n${names.join(", ")}\n\nThis cannot be undone.` }),
      onConfirm: async () => {
        confirm = null;
        batchLoading = true;
        let ok_count = 0;
        for (const name of names) {
          try { await volumesApi.removeVolume(name, true); ok_count++; } catch {}
        }
        globalToast("success", `Removed ${ok_count} volume(s)`);
        selected = new Set();
        batchLoading = false;
        refreshVolumes();
      },
      onCancel: () => { confirm = null; }
    };
  }

  function toggleSelect(name: string) {
    const next = new Set(selected);
    next.has(name) ? next.delete(name) : next.add(name);
    selected = next;
  }

  let filteredVolumes = $derived(resourceState.volumes.filter(v => 
    v.Name.toLowerCase().includes(searchTerm.toLowerCase()) || 
    v.Driver.toLowerCase().includes(searchTerm.toLowerCase())
  ));

</script>

<div class="content-header">
  <h1>
    {t('volumes.title', { default: 'Volumes' })}
    <span style="font-size: var(--text-sm); color: var(--text-muted); font-weight: 400; margin-left: 12px;">
      {resourceState.volumes.length} {t('volumes.count_label', { default: 'volume(s)' })}
    </span>
    {#if runtimeName}
      <span style="font-size: var(--text-xs); background: var(--bg-secondary); border: 1px solid var(--border-primary); padding: 2px 8px; border-radius: 12px; margin-left: 12px; color: var(--text-muted);">
        {#if runtimeName === "podman"}
          🦭 Podman
        {:else if runtimeName === "containerd"}
          📦 Containerd
        {:else}
          {@html Icons.Docker} Docker
        {/if}
      </span>
    {/if}
  </h1>
  <div class="content-header-actions">
    {#if selected.size > 0}
      <button class="btn btn-ghost" style="color: var(--accent-red); font-size: var(--text-sm);" onclick={handleBatchRemove} disabled={batchLoading}>
        {batchLoading ? t('volumes.removing', { default: 'Removing...' }) : t('volumes.remove_selected', { default: `Remove ${selected.size} Selected` })}
      </button>
    {/if}
    <button class="btn btn-ghost" onclick={handlePrune} disabled={actionLoading === "prune"}>
      {actionLoading === "prune" ? t('volumes.pruning', { default: 'Pruning...' }) : t('volumes.prune', { default: 'Prune' })}
    </button>
    <button class="btn btn-primary" onclick={() => showCreate = !showCreate}>
      + {t('volumes.create_button', { default: 'Create Volume' })}
    </button>
    <button class="btn btn-ghost" onclick={refreshVolumes}>↻ {t('volumes.refresh', { default: 'Refresh' })}</button>
  </div>
</div>

<div class="content-body">
  {#if showCreate}
    <div style="padding: 16px; background: var(--bg-secondary); border-radius: 12px; margin-bottom: 16px; border: 1px solid var(--border-primary);">
      <h3 style="margin: 0 0 12px; font-size: var(--text-base);">{t('volumes.create_title', { default: 'Create Volume' })}</h3>
      <div style="display: flex; gap: 12px; align-items: flex-end;">
        <div style="flex: 1;">
          <label for="volName" style="display: block; font-size: var(--text-sm); color: var(--text-secondary); margin-bottom: 4px;">{t('volumes.name', { default: 'Name' })}</label>
          <input id="volName" type="text" bind:value={newName} placeholder="my-volume" style="width: 100%; padding: 8px 12px; background: var(--bg-primary); border: 1px solid var(--border-primary); border-radius: 6px; color: var(--text-primary); font-size: var(--text-sm);" onkeydown={(e) => e.key === 'Enter' && handleCreate()} />
        </div>
        <div>
          <label for="volDriver" style="display: block; font-size: var(--text-sm); color: var(--text-secondary); margin-bottom: 4px;">{t('volumes.driver', { default: 'Driver' })}</label>
          <select id="volDriver" bind:value={newDriver} class="input select">
            <option value="local">local</option>
          </select>
        </div>
        <button class="btn btn-primary" onclick={handleCreate} disabled={actionLoading === "create" || !newName.trim()}>
          {actionLoading === "create" ? t('volumes.creating', { default: 'Creating...' }) : t('volumes.create', { default: 'Create' })}
        </button>
        <button class="btn btn-ghost" onclick={() => showCreate = false}>{t('volumes.cancel', { default: 'Cancel' })}</button>
      </div>
    </div>
  {/if}

  <div style="margin-bottom: 16px;">
    <input type="text" bind:value={searchTerm} placeholder={t('volumes.search', { default: 'Search volumes...' })} style="width: 100%; padding: 8px 12px; background: var(--bg-secondary); border: 1px solid var(--border-primary); border-radius: 8px; color: var(--text-primary); font-size: var(--text-sm);" />
  </div>

  {#if resourceState.volumesLoading}
    <div style="text-align: center; padding: 40px; color: var(--text-muted);">{t('volumes.loading', { default: 'Loading volumes...' })}</div>
  {:else if filteredVolumes.length === 0}
    <div style="text-align: center; padding: 40px; color: var(--text-muted);">
      {searchTerm ? t('volumes.no_search', { default: 'No volumes match your search' }) : t('volumes.no_found', { default: 'No volumes found' })}
    </div>
  {:else}
    <div style="display: flex; flex-direction: column; gap: 8px;">
      {#each filteredVolumes as vol (vol.Name)}
        {@const formatted = formatVolumeName(vol.Name)}
        <div style="padding: 16px; background: {selected.has(vol.Name) ? 'rgba(88,166,255,0.06)' : 'var(--bg-secondary)'}; border-radius: 12px; border: {selected.has(vol.Name) ? '1px solid rgba(88,166,255,0.25)' : '1px solid var(--border-primary)'}; transition: all 150ms;">
          <div style="display: flex; justify-content: space-between; align-items: center; gap: 12px;">
            <div style="display: flex; align-items: center; gap: 10px; flex: 1; min-width: 0;">
              <input type="checkbox" class="checkbox" checked={selected.has(vol.Name)} onchange={() => toggleSelect(vol.Name)} />
              <div style="min-width: 0;">
                <div style="font-weight: 600; font-size: var(--text-base); overflow: hidden; text-overflow: ellipsis; white-space: nowrap;" title={vol.Name}>
                  {#if formatted.isHash}
                    <span style="font-family: var(--font-mono); font-size: var(--text-sm); color: var(--text-secondary);">{formatted.display}</span>
                  {:else}
                    {formatted.display}
                  {/if}
                </div>
                <div style="color: var(--text-muted); font-size: var(--text-sm); margin-top: 4px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;" title={`Driver: ${vol.Driver}${vol.Scope ? ` · Scope: ${vol.Scope}` : ''}${vol.Mountpoint ? ` · ${vol.Mountpoint}` : ''}`}>
                  {t('volumes.driver', { default: 'Driver' })}: <span style="color: var(--accent-blue);">{vol.Driver}</span>
                  {#if vol.Scope} · {t('volumes.scope', { default: 'Scope' })}: {vol.Scope}{/if}
                  {#if vol.Mountpoint} · {vol.Mountpoint}{/if}
                </div>
              </div>
            </div>
            <div style="display: flex; gap: 6px; flex-shrink: 0;">
              <button class="btn btn-ghost" onclick={() => handleInspect(vol.Name)} style="font-size: var(--text-xs); padding: 4px 10px;">
                {inspecting === vol.Name ? "Hide" : "Inspect"}
              </button>
              <button class="btn btn-ghost" onclick={() => handleRemove(vol.Name)} disabled={actionLoading === vol.Name} style="font-size: var(--text-xs); padding: 4px 10px; color: var(--accent-red);">
                {actionLoading === vol.Name ? "..." : "Remove"}
              </button>
            </div>
          </div>
          {#if inspecting === vol.Name}
            <pre style="margin-top: 12px; padding: 12px; background: var(--bg-primary); border-radius: 8px; font-size: var(--text-xs); overflow: auto; max-height: 300px; color: var(--text-secondary);">{inspectData}</pre>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>

{#if confirm}
  <div role="button" tabindex="0" class="modal-overlay" onkeydown={(e) => e.key === 'Enter' && e.currentTarget.click()} onclick={() => confirm?.onCancel?.()}>
    <div role="button" tabindex="0" class="modal" onkeydown={(e) => e.key === 'Enter' && e.currentTarget.click()} onclick={(e) => e.stopPropagation()} style="width: min(400px, 90vw);">
      <div class="modal-header"><h2 class="modal-title">{confirm.title}</h2></div>
      <p style="color: var(--text-secondary); font-size: var(--text-sm); line-height: 1.6;">{confirm.message}</p>
      <div class="modal-footer">
        <button class="btn btn-ghost" onclick={() => confirm?.onCancel?.()}>Cancel</button>
        <button class="btn {confirm.danger ? 'btn-danger' : 'btn-primary'}" onclick={() => confirm?.onConfirm()}>{confirm.confirmLabel}</button>
      </div>
    </div>
  </div>
{/if}

// src/pages/Volumes.tsx
import { useState, useEffect, useCallback, useDeferredValue } from "react";
import { volumesApi } from "../lib/api";
import { ConfirmDialog, useConfirm } from "../components/ConfirmDialog";
import { BroomIcon, WarningIcon } from "../components/Icons";
import { formatVolumeName } from "../lib/formatters";
import { useAtom } from "jotai";
import { volumesAtom, volumesLoadingAtom } from "../store/resourceAtom";

interface VolumesProps {}

export default function Volumes(_props: VolumesProps) {
  const [volumes, setVolumes] = useAtom(volumesAtom);
  const [loading, setLoading] = useAtom(volumesLoadingAtom);
  const [error, setError] = useState<string | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [newName, setNewName] = useState("");
  const [newDriver, setNewDriver] = useState("local");
  const [inspecting, setInspecting] = useState<string | null>(null);
  const [inspectData, setInspectData] = useState<string>("");
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const deferredSearch = useDeferredValue(search);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [batchLoading, setBatchLoading] = useState(false);
  const { confirm, ConfirmDialogProps } = useConfirm();

  const refresh = useCallback(async () => {
    try {
      setError(null);
      const list = await volumesApi.listVolumes();
      setVolumes(list);
    } catch (e) {
      setError(String(e));
      setVolumes([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  const handleCreate = async () => {
    if (!newName.trim()) return;
    setActionLoading("create");
    try {
      await volumesApi.createVolume(newName.trim(), newDriver);
      setNewName("");
      setShowCreate(false);
      await refresh();
    } catch (e) {
      setError(String(e));
    } finally {
      setActionLoading(null);
    }
  };

  const handleRemove = async (name: string) => {
    const ok = await confirm({ title: "Remove Volume", message: `Remove volume "${name}"?`, confirmText: "Remove", variant: "danger" });
    if (!ok) return;
    setActionLoading(name);
    try {
      await volumesApi.removeVolume(name, true);
      setSelected(new Set());
      await refresh();
    } catch (e) {
      setError(String(e));
    } finally {
      setActionLoading(null);
    }
  };

  const handlePrune = async () => {
    const ok = await confirm({ title: "Prune Volumes", message: "Remove all unused volumes? This cannot be undone.", confirmText: "Prune All", variant: "warning" });
    if (!ok) return;
    setActionLoading("prune");
    try {
      await volumesApi.pruneVolumes();
      setSelected(new Set());
      await refresh();
    } catch (e) {
      setError(String(e));
    } finally {
      setActionLoading(null);
    }
  };

  const handleInspect = async (name: string) => {
    if (inspecting === name) { setInspecting(null); return; }
    try {
      const data = await volumesApi.inspectVolume(name);
      setInspectData(data);
      setInspecting(name);
    } catch (e) {
      setError(String(e));
    }
  };

  const filtered = volumes.filter(v =>
    v.Name.toLowerCase().includes(deferredSearch.toLowerCase()) ||
    v.Driver.toLowerCase().includes(deferredSearch.toLowerCase())
  );

  useEffect(() => { setSelected(new Set()); }, [search]);

  // Auto-cleanup: remove stale selections when data changes
  useEffect(() => {
    setSelected(prev => {
      const validNames = new Set(volumes.map(v => v.Name));
      const next = new Set([...prev].filter(name => validNames.has(name)));
      return next.size !== prev.size ? next : prev;
    });
  }, [volumes]);

  const toggleSelect = (name: string) => setSelected(prev => {
    const next = new Set(prev);
    next.has(name) ? next.delete(name) : next.add(name);
    return next;
  });


  const handleBatchRemove = async () => {
    const names = filtered.filter(v => selected.has(v.Name)).map(v => v.Name);
    if (names.length === 0) return;
    const ok = await confirm({ title: "Remove Selected Volumes", message: `Remove ${names.length} volume${names.length > 1 ? "s" : ""}?\n\n${names.join(", ")}\n\nThis cannot be undone.`, confirmText: `Remove ${names.length}`, variant: "danger" });
    if (!ok) return;
    setBatchLoading(true);
    let ok_count = 0;
    for (const name of names) {
      try { await volumesApi.removeVolume(name, true); ok_count++; } catch { /* continue */ }
    }
    setSelected(new Set());
    setBatchLoading(false);
    refresh();
  };

  return (
    <div style={{ padding: "24px" }}>
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
        <div>
          <h2 style={{ margin: 0, fontSize: "var(--text-xl)", fontWeight: 600 }}>Volumes</h2>
          <p style={{ margin: "4px 0 0", color: "var(--text-muted)", fontSize: "var(--text-sm)" }}>
            {volumes.length} volume{volumes.length !== 1 ? "s" : ""}
          </p>
        </div>
        <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
          {selected.size > 0 && (
            <button className="btn btn-ghost" style={{ color: "var(--accent-red)", fontSize: "var(--text-sm)" }}
              onClick={handleBatchRemove} disabled={batchLoading}>
              {batchLoading ? "Removing..." : `Remove ${selected.size} Selected`}
            </button>
          )}
          <button className="btn btn-ghost" onClick={handlePrune} disabled={actionLoading === "prune"}
            style={{ display: "flex", alignItems: "center", gap: 4 }}>
            {actionLoading === "prune" ? "Pruning..." : <><BroomIcon size={12} style={{ display: "inline", verticalAlign: "middle" }} /> Prune</>}
          </button>
          <button className="btn btn-primary" onClick={() => setShowCreate(!showCreate)}>
            + Create Volume
          </button>
          <button className="btn btn-ghost" onClick={refresh}>↻ Refresh</button>
        </div>
      </div>

      {/* Error */}
      {error && (
        <div style={{ padding: "12px", background: "rgba(248,81,73,0.1)", color: "var(--accent-red)", borderRadius: "8px", marginBottom: "16px", fontSize: "var(--text-sm)" }}>
          <WarningIcon size={14} style={{ display: "inline", verticalAlign: "middle", marginRight: 4 }} /> {error}
          <button className="btn btn-ghost" style={{ marginLeft: "8px", fontSize: "var(--text-xs)" }} onClick={() => setError(null)}>Dismiss</button>
        </div>
      )}

      {/* Create form */}
      {showCreate && (
        <div style={{ padding: "16px", background: "var(--bg-secondary)", borderRadius: "12px", marginBottom: "16px", border: "1px solid var(--border-primary)" }}>
          <h3 style={{ margin: "0 0 12px", fontSize: "var(--text-base)" }}>Create Volume</h3>
          <div style={{ display: "flex", gap: "12px", alignItems: "flex-end" }}>
            <div style={{ flex: 1 }}>
              <label style={{ display: "block", fontSize: "var(--text-sm)", color: "var(--text-secondary)", marginBottom: "4px" }}>Name</label>
              <input
                type="text"
                value={newName}
                onChange={e => setNewName(e.target.value)}
                placeholder="my-volume"
                style={{ width: "100%", padding: "8px 12px", background: "var(--bg-primary)", border: "1px solid var(--border-primary)", borderRadius: "6px", color: "var(--text-primary)", fontSize: "var(--text-sm)" }}
                onKeyDown={e => e.key === "Enter" && handleCreate()}
              />
            </div>
            <div>
              <label style={{ display: "block", fontSize: "var(--text-sm)", color: "var(--text-secondary)", marginBottom: "4px" }}>Driver</label>
              <select
                value={newDriver}
                onChange={e => setNewDriver(e.target.value)}
                style={{ padding: "8px 12px", background: "var(--bg-primary)", border: "1px solid var(--border-primary)", borderRadius: "6px", color: "var(--text-primary)", fontSize: "var(--text-sm)" }}
              >
                <option value="local">local</option>
              </select>
            </div>
            <button className="btn btn-primary" onClick={handleCreate} disabled={actionLoading === "create" || !newName.trim()}>
              {actionLoading === "create" ? "Creating..." : "Create"}
            </button>
            <button className="btn btn-ghost" onClick={() => setShowCreate(false)}>Cancel</button>
          </div>
        </div>
      )}

      {/* Search */}
      <div style={{ marginBottom: "16px" }}>
        <input
          type="text"
          value={search}
          onChange={e => setSearch(e.target.value)}
          placeholder="Search volumes..."
          style={{ width: "100%", padding: "8px 12px", background: "var(--bg-secondary)", border: "1px solid var(--border-primary)", borderRadius: "8px", color: "var(--text-primary)", fontSize: "var(--text-sm)" }}
        />
      </div>

      {/* Volume list */}
      {loading ? (
        <div style={{ textAlign: "center", padding: "40px", color: "var(--text-muted)" }}>Loading volumes...</div>
      ) : filtered.length === 0 ? (
        <div style={{ textAlign: "center", padding: "40px", color: "var(--text-muted)" }}>
          {search ? "No volumes match your search" : "No volumes found"}
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
          {filtered.map(vol => (
            <div key={vol.Name} style={{ padding: "16px", background: selected.has(vol.Name) ? "rgba(88,166,255,0.06)" : "var(--bg-secondary)", borderRadius: "12px", border: selected.has(vol.Name) ? "1px solid rgba(88,166,255,0.25)" : "1px solid var(--border-primary)", transition: "all 150ms" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  <input type="checkbox" checked={selected.has(vol.Name)} onChange={() => toggleSelect(vol.Name)}
                    style={{ accentColor: "var(--accent-blue)", cursor: "pointer" }} />
                  <div>
                    {(() => {
                      const { display, isHash } = formatVolumeName(vol.Name);
                      return (
                        <div style={{ fontWeight: 600, fontSize: "var(--text-base)", maxWidth: '500px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={vol.Name}>
                          {isHash ? (
                            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-sm)', color: 'var(--text-secondary)' }}>{display}</span>
                          ) : display}
                        </div>
                      );
                    })()}
                  <div style={{ color: "var(--text-muted)", fontSize: "var(--text-sm)", marginTop: "4px", maxWidth: '600px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}
                    title={`Driver: ${vol.Driver}${vol.Scope ? ` · Scope: ${vol.Scope}` : ''}${vol.Mountpoint ? ` · ${vol.Mountpoint}` : ''}`}>
                    Driver: <span style={{ color: "var(--accent-blue)" }}>{vol.Driver}</span>
                    {vol.Scope && <> · Scope: {vol.Scope}</>}
                    {vol.Mountpoint && <> · {vol.Mountpoint}</>}
                  </div>
                </div>
                <div style={{ display: "flex", gap: "6px" }}>
                  <button className="btn btn-ghost" onClick={() => handleInspect(vol.Name)} style={{ fontSize: "var(--text-xs)", padding: "4px 10px" }}>
                    {inspecting === vol.Name ? "Hide" : "Inspect"}
                  </button>
                  <button
                    className="btn btn-ghost"
                    onClick={() => handleRemove(vol.Name)}
                    disabled={actionLoading === vol.Name}
                    style={{ fontSize: "var(--text-xs)", padding: "4px 10px", color: "var(--accent-red)" }}
                  >
                    {actionLoading === vol.Name ? "..." : "Remove"}
                  </button>
                </div>
              </div>
              </div>
              {inspecting === vol.Name && (
                <pre style={{ marginTop: "12px", padding: "12px", background: "var(--bg-primary)", borderRadius: "8px", fontSize: "var(--text-xs)", overflow: "auto", maxHeight: "300px", color: "var(--text-secondary)" }}>
                  {inspectData}
                </pre>
              )}
            </div>
          ))}
        </div>
      )}
      <ConfirmDialog {...ConfirmDialogProps} />
    </div>
  );
}
